# -*- coding: utf-8 -*-
"""Project-5.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ISqp1SaB-CjnpLJTTfducspB1W4Hx6ue
"""

import scipy.stats as stats

# Calculate the probability of observing 12 or more days of rain in the next 30 days when expected was 10
prob_more_than_12 = 1 - stats.poisson.cdf(12, 10)
print("Probability of raining more than 12 days, is", prob_more_than_12)

# Calculate the probability of observing 12 and 18 days of rain
prob_12_to_18 = stats.poisson.cdf(18, 10) - stats.poisson.cdf(11, 10)
print("Probability of raining between 12 and 18 days, is", prob_12_to_18)